- name: install debconf utils
  ansible.builtin.apt:
    name: 
      - debconf-utils
    state: present
  become: true

- name: preseed slapd
  block:
  - name: preseed slapd | set domain
    ansible.builtin.debconf:
      name: slapd
      question: slapd/domain
      value: '{{ domain_name }}'
      vtype: string
    become: true
    register: slapd_config

  - name: preseed slapd | set org
    ansible.builtin.debconf:
      name: slapd
      question: shared/organization
      value: '{{ organization }}'
      vtype: string
    become: true
    register: slapd_config

- name: install slapd and utilities
  ansible.builtin.apt:
    name: 
      - slapd
      - ldap-utils
      - python3-ldap
    state: present
  become: true

- name: reconfigure slapd
  ansible.builtin.command:
    cmd: "dpkg-reconfigure slapd"
  environment:
    DEBIAN_FRONTEND: noninteractive
  become: true
  when: slapd_config is changed

- name: import letsencrypt role
  ansible.builtin.import_role:
    name: letsencrypt

- name: configure tls
  community.general.ldap_attrs:
    dn: cn=config
    attributes:
      olcTLSCertificateFile: "/etc/ldap/ldap.{{ domain_name }}.crt"
      olcTLSCertificateKeyFile:  "/etc/ldap/ldap.{{ domain_name }}.key"
      olcTLSCACertificateFile: "/etc/ldap/ldap.{{ domain_name }}_chain.crt" 
    state: exact
  become: true
  register: tls_attrs

- name: enable ldaps and disable ldap
  ansible.builtin.lineinfile:
    path: /etc/default/slapd
    regexp: '^SLAPD_SERVICES=.*'
    line: 'SLAPD_SERVICES="ldapi:/// ldaps:///"'
  become: true
  register: slapd_config

- name: restart slapd
  ansible.builtin.systemd_service:
    state: restarted
    name: slapd
  become: true
  when: slapd_config is changed or tls_attrs is changed

- name: check if admin exists
  community.general.ldap_search:
    dn: "olcDatabase={1}mdb,cn=config"
    attrs:
      - "olcRootDN"
      - "olcRootPW"
  become: true
  register: admin_attrs

- name: remove olcRootDN
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcRootDN: "{{ admin_attrs.results.0.olcRootDN }}"
    state: absent
  become: true
  when: "'olcRootDN' in admin_attrs.results.0"

- name: remove olcRootPW
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcRootPW: "{{ admin_attrs.results.0.olcRootPW }}"
    state: absent
  become: true
  when: "'olcRootPW' in admin_attrs.results.0"

- name: setup acls
  community.general.ldap_attrs:
    dn: olcDatabase={1}mdb,cn=config
    attributes:
      olcAccess:
        - >-
          {0}to attrs=userPassword
          by self write 
          by anonymous auth
          by * none
        - >-
          {1}to attrs=shadowLastChange
          by self write
        - >-
          {2}to *
          by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
          by group.exact=cn=ops,ou=groups,{{ dc }} manage
          by dn=cn=readonly,ou=users,{{ dc }} read
    state: exact
  become: true

- name: create users ou
  community.general.ldap_entry:
    dn: ou=users,{{ dc }}
    objectClass: organizationalUnit
  become: true

- name: create readonly user
  community.general.ldap_entry:
    dn: cn=readonly,ou=users,{{ dc }}
    objectClass:
      - simpleSecurityObject
      - organizationalRole
    attributes:
      description: readonly user
      userPassword: "{SSHA}85DcSf+o3K7gLAiT0slGsF2BZXE0BNvg"
  become: true

- name: create sysadmin user
  community.general.ldap_entry:
    dn: uid=sysadmin,ou=users,{{ dc }}
    objectClass:
      - iNetOrgPerson
    attributes:
      description: system administrator
      cn: system
      sn: administrator
      o: homelab
      mail: "sysadmin@{{ domain_name }}"
      userPassword: "{SSHA}M3044THc2hT0wq8d+UwiSNqU7u29wCU3"
  become: true

- name: create groups ou
  community.general.ldap_entry:
    dn: ou=groups,{{ dc }}
    objectClass: organizationalUnit
    attributes:
      member: uid=sysadmin,ou=users,{{ dc }}
  become: true

- name: create ops group
  community.general.ldap_entry:
    dn: cn=ops,ou=groups,{{ dc }}
    objectClass: groupOfNames
    attributes:
      member: uid=sysadmin,ou=users,{{ dc }}
  become: true

- name: install and configure phpldapadmin
  ansible.builtin.include_tasks:
    file: phpldapadmin.yml
