resource_types:
- name: ansible-playbook
  type: docker-image
  source:
    repository: troykinsella/concourse-ansible-playbook-resource
    tag: latest

resources:
- name: manual-trigger
  type: time
  source:
    interval: 1m
- name: daily-trigger
  type: time
  source:
    start: 1:00 AM
    stop: 2:00 AM
    location: America/New_York
- name: homelab-automation
  type: git
  source:
    uri: https://github.com/samchelini/homelab-automation.git
    branch: main
- name: ansible
  type: ansible-playbook
  source:
    user: ansible
    ssh_private_key: ((ansible.private_key))
    vault_password: ((ansible.vault_password))

jobs:
- name: manual-trigger
  plan:
  - put: manual-trigger
- name: update-vms
  plan:
  - get: manual-trigger
    trigger: true
    passed:
      - manual-trigger
  - get: daily-trigger
    trigger: true
  - get: homelab-automation
  - put: ansible
    params:
      inventory: hosts
      playbook: update-vms.yml
      path: homelab-automation/ansible
